name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet
      env:
        GCLOUD_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

