name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install production dependencies
      run: pip install -r requirements.txt
    
    - name: Install development dependencies
      run: pip install -r requirements-dev.txt
    
    - name: Install test dependencies
      run: pip install -r requirements-test.txt
    
    - name: Run unit tests
      run: pytest

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: reports/html
